version: '3.9'

services:
  mariadb:
    image: mariadb:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - backend-network
  bookmedik:
    image: sercamjav/bookmedik:v1
    restart: always
    ports:
      - "8080:80"
    environment:
      DB_HOST: ${DB_HOST}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - mariadb
    networks:
      - frontend-network
      - backend-network
volumes:
  mariadb_data:

networks:
  frontend-network:
    driver: bridge
  backend-network:
    driver: bridge
